name: what3words
description: >-
  A Dart library to use the what3words v3 API. This library can either be used in native Dart or Flutter applications
version: 3.0.5
homepage: https://github.com/what3words/w3w-dart-wrapper

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
 chopper: ^4.0.0-nullsafety.0
 json_serializable: ^4.1.0
 json_annotation: ^4.0.1
 os_detect: ^1.0.0

dev_dependencies:
  build_runner: ^1.9.0
  chopper_generator: ^4.0.0-nullsafety.0
  pedantic: ^1.11.0
  test: ^1.15.4
